spring:
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 20
        min-idle: 0
      timeout: 2000
redis:
  cache:
    enable: false
    expression: public * com.lazyboyl.cache.example.service.*.*(..)
